/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Courses {
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  image: string | null;
  price_uzs: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Dictionaries {
  category_id: string;
  created_at: Generated<Timestamp>;
  example_en: string;
  example_pronunciation: string;
  example_ru: string;
  example_uz: string;
  example_zh: string;
  id: Generated<string>;
  lesson_id: string | null;
  pronunciation: string;
  updated_at: Generated<Timestamp>;
  word_en: string;
  word_ru: string;
  word_uz: string;
  word_zh: string;
}

export interface DictionaryCategories {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name_en: string;
  name_ru: string;
  name_uz: string;
  updated_at: Generated<Timestamp>;
}

export interface Enrollments {
  course_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  user_id: string;
}

export interface Grammars {
  created_at: Generated<Timestamp>;
  description: string;
  example: string;
  example_en: string;
  example_ru: string;
  example_uz: string;
  id: Generated<string>;
  lesson_id: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Lessons {
  course_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  title_en: string;
  title_ru: string;
  title_uz: string;
  updated_at: Generated<Timestamp>;
  video: string | null;
}

export interface Reviews {
  comment: string;
  course_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  refresh_token_hash: string;
  user_id: string;
}

export interface Stories {
  content: string;
  content_en: string;
  content_ru: string;
  content_uz: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: string;
  title: string;
  title_en: string;
  title_ru: string;
  title_uz: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  avatar: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  password_hash: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  courses: Courses;
  dictionaries: Dictionaries;
  dictionary_categories: DictionaryCategories;
  enrollments: Enrollments;
  grammars: Grammars;
  lessons: Lessons;
  reviews: Reviews;
  sessions: Sessions;
  stories: Stories;
  users: Users;
}
